name: Test Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install node v17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test
